# Usa a imagem base do Python
FROM python:3.11-slim-buster

# Define o diretório de trabalho dentro do contêiner
WORKDIR /app

# Instala as dependências necessárias para o Selenium e o Chromium
# Certifique-se de que o chromium-driver está corretamente ligado/no PATH para o Selenium
RUN apt-get update && apt-get install -y \
    chromium \
    chromium-driver \
    --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

# Copia o arquivo requirements.txt e instala as dependências Python
# Mova a cópia do requirements.txt para ANTES do pip install
# Copie todo o conteúdo da pasta 'parque' (que é o 'context' do build) para '/app'
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copia o restante dos arquivos do seu projeto (incluindo db_utils)
# A pasta 'parque' do host (seu contexto de build) será copiada para /app no container
COPY . /app

# Define o comando para executar o parquedosleiloes.py
CMD ["python3", "parquedosleiloes.py"]